name: Build and Test

on:
  pull_request:
    branches: [ "stable" ]
  push:
    branches: [ "stable" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-and-test-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        
    steps:
      - uses: actions/checkout@master
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Create virtual environment
        run: python -m venv airgym-env
          
      - name: Activate venv and install requirements
        run: |
          source airgym-env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linter
        run: |
          python -m pip install pylint
          pylint **/*.py
        continue-on-error: true
          
      - name: Install build and Pypa
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .