name: Release to PyPI when a release is created

on:
  release:
    types: [released]

jobs:

  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@master
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Create virtual environment
        run: python -m venv airgym-env
      
      - name: Activate virtual environment
        run: |
          source airgym-env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install build and Pypa
        run: python -m pip install build --user
          
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}